Mark/stop getting file list
CARTAvis/carta-protobuf pull request #48
Opened 2021-04-30 09:12 UTC by veggiesaurus

2021-04-30 09:44 UTC, confluence commented
@markccchiang How are you updating `docs/src/defs.rst.txt`, `docs/src/enums.rst.txt` and `docs/src/messages.rst.txt`? These should be updated automatically from the `.proto` files by the makefile in `doc/protoc` (you should just run `make` in that directory to regenerate them). Whenever I do this locally, the files I get are changed; for example, the ordering of the messages is different. Are you perhaps modifying these by hand?

2021-04-30 09:53 UTC, veggiesaurus commented on shared/enums.proto
> +    STOP_FILE_LIST = 71;
@markccchiang can we have a single message with a file type parameter in order to cancel either the image file list or the catalog file list.

2021-04-30 09:53 UTC, veggiesaurus commented on shared/enums.proto
> +    FILE_LIST_PROGRESS = 73;
I don't see why we need three separate progress messages that effectively do the same thing. Just make a `FILE_LIST_PROGRESS` event with a `FileListProgress` message which contains a file type parameter.

2021-04-30 09:53 UTC, confluence commented
To save time I will push the updated files from here.

2021-04-30 09:53 UTC, veggiesaurus commented
@markccchiang please see PR comments

2021-04-30 10:02 UTC, confluence requested changes

2021-04-30 10:02 UTC, confluence commented on docs/src/defs.rst.txt
> +.. carta:class:: carta-sub progress
Please see my comments about updating these files. You should be running `make` in `docs/protoc` to generate them automatically. You need to have `protoc` installed. The Python script used by the makefile automatically sorts these messages by name.

2021-04-30 10:02 UTC, confluence commented on docs/src/messages.rst.txt
> +     - Whether the Catalog list process is canceled or not
"Catalog" should not be capitalised

2021-04-30 10:02 UTC, confluence commented on docs/src/messages.rst.txt
> +     - Whether the Catalog list process is canceled or not
A minor point, but "canceled" is the American spelling, and I think we normally use British (which would be "cancelled"). But I'm not 100% sure what we've standardised on.

2021-04-30 10:02 UTC, confluence commented on shared/defs.proto
> +message Progress {
Could we give this a more specific name, and also more documentation in the comments? Out of context it's unclear what this message is for.

2021-04-30 10:02 UTC, confluence commented on docs/src/messages.rst.txt
> +     - Whether the Catalog list process is canceled or not
These descriptions should go in comments in the proto files; when these docs are generated they are included automatically.

2021-04-30 10:04 UTC, confluence commented on shared/defs.proto
> +message Progress {
All of these proto file additions should be commented -- the docs are automatically generated from these comments. Any descriptions that are written by hand only into the docs are going to disappear the next time the docs are regenerated.

2021-04-30 10:14 UTC, confluence commented on shared/defs.proto
> +message Progress {
Perhaps `ListProgress` would be an appropriate generic name. I agree with @angus that there should be only one event type.

2021-05-02 17:02 UTC, markccchiang commented
> @markccchiang How are you updating `docs/src/defs.rst.txt`, `docs/src/enums.rst.txt` and `docs/src/messages.rst.txt`? These should be updated automatically from the `.proto` files by the makefile in `doc/protoc` (you should just run `make` in that directory to regenerate them). Whenever I do this locally, the files I get are changed; for example, the ordering of the messages is different. Are you perhaps modifying these by hand?

Thank you for the reminder! I have corrected these text files by automatic generation script.

2021-05-03 08:34 UTC, confluence requested changes
This change removes field descriptions from the documentation which were previously added only to the hand-edited `.rst.txt` files and not to the `.proto` files. This applies both to the current changes and to the previous messages added in the Stokes concatenation PR. Please add these as comments to the `.proto` files, so that when the  `.rst.txt` files are regenerated they contain the descriptions.

2021-05-03 08:39 UTC, confluence commented
I would actually recommend fixing the Stokes concatenation docs in a separate PR -- splitting out these sets of unrelated changes would make them easier to review. If you are going to do that, please also remove the unnecessary import of `defs.proto` from `control/concat_stokes_files.proto`.

2021-05-03 21:07 UTC, confluence commented
The other PR has been merged -- please merge the latest dev into this branch and also re-run the protoc makefile. That should fix the diff.

2021-05-04 08:48 UTC, confluence approved these changes
Looks fine to me.

2021-05-05 07:58 UTC, merged