Jason/issue 1130
CARTAvis/carta-protobuf pull request #53
Opened 2021-07-16 09:28 UTC by duidae

companion PR for ping pong test of spectral line query widget

2021-07-22 10:00 UTC, veggiesaurus commented
@duidae you will need to add a changelog entry for this and bump the minor version number (since this is a non-breaking change)

Perhaps it would be good to describe what's happening in a sequence diagram as well?

2021-07-22 10:02 UTC, confluence requested changes
Please regenerate the automatic message documentation: run `make` in `docs/protoc`.

2021-07-23 07:25 UTC, confluence approved these changes

2021-07-23 09:22 UTC, veggiesaurus requested changes
please add an entry to the [changelog ](https://github.com/CARTAvis/carta-protobuf/blob/dev/docs/src/changelog.rst.txt) bump version number to `23.1.0` in [index.rst](https://github.com/CARTAvis/carta-protobuf/blob/dev/docs/src/index.rst)

2021-07-23 09:40 UTC, veggiesaurus approved these changes

2021-07-23 09:52 UTC, merged