Modify the ContourImageData message
CARTAvis/carta-protobuf pull request #58
Opened 2021-10-25 15:38 UTC by markccchiang

It is to fit the frontend requirement in the frontend [PR 1636](https://github.com/CARTAvis/carta-frontend/pull/1636). A new bool variable `is_long_task` is added to the contour data message. `is_long_task=true` if the estimated time of the contour process is greater than 1 second. It decides whether to show the contour progress bar in the frontend. The `.txt` files are also modified by regenerating them automatically.

2021-10-29 11:01 UTC, confluence requested changes
This also requires a manual entry in `docs/src/changelog.rst.txt`. This should be a minor version bump (because it adds a new feature, but it's not a breaking change).

2021-10-29 20:38 UTC, confluence commented
Guidelines for versioning have just been merged, also into the changelog file -- so please merge `dev` into this branch as well.

2021-11-02 07:21 UTC, confluence approved these changes

2021-12-06 07:13 UTC, veggiesaurus commented
marked as draft, as we're not sure if it's needed by the frontend anymore

2022-03-23 01:59 UTC, closed without merging