Add PV generator messages
CARTAvis/carta-protobuf pull request #62
Opened 2021-12-03 16:06 UTC by pford

2021-12-06 07:02 UTC, veggiesaurus requested changes

2021-12-06 07:02 UTC, veggiesaurus commented on docs/src/changelog.rst.txt
> +   * - ``24.3.0``
I guess technically the changes in this PR are non-breaking, but I think we should also bump the ICD version (and thus the major version of the protobufs) when we introduce major new sets of messages like this. There's precedent for this (e.g. the concatenated messages above)

2021-12-06 08:21 UTC, confluence requested changes
The documents need to be regenerated (with `make` in `docs/protoc`).

2021-12-06 20:35 UTC, confluence approved these changes

2021-12-08 06:25 UTC, veggiesaurus approved these changes

2021-12-09 06:31 UTC, merged