Yuhsuan/fov fitting
CARTAvis/carta-protobuf pull request #74
Opened 2022-06-17 07:32 UTC by YuHsuan-Hwang

Add messages for requesting image fitting with field of view.
Companion PR: https://github.com/CARTAvis/carta-backend/pull/1128

2022-06-24 12:13 UTC, confluence requested changes

2022-06-24 12:13 UTC, confluence commented on docs/src/changelog.rst.txt
> +   * - ``28.1.0``
This also needs to be bumped in `index.rst`.

2022-06-28 01:59 UTC, YuHsuan-Hwang commented on docs/src/changelog.rst.txt
> +   * - ``28.1.0``
fixed

2022-06-28 07:20 UTC, confluence approved these changes

2022-06-28 08:14 UTC, veggiesaurus approved these changes

2022-06-30 08:52 UTC, merged