Mark/add axes numbers
CARTAvis/carta-protobuf pull request #77
Opened 2022-11-29 06:04 UTC by markccchiang

This adds a new sub-message `AxesNumbers` in the message `FileInfoExtended` and passes it to the frontend. So the frontend can decide which axes to be rendered (axis number is 0 or 1). And which is the depth axis (axis number > 1) for non-stokes axis. This is for the backend [PR 1194](https://github.com/CARTAvis/carta-backend/pull/1194) and the frontend [PR 2011](https://github.com/CARTAvis/carta-frontend/pull/2011).

2022-11-29 17:06 UTC, pford commented
@markccchiang don't forget the changelog

2023-03-13 09:12 UTC, confluence requested changes
Minor changes requested.

2023-03-13 09:12 UTC, confluence commented on docs/src/index.rst
> +:CARTA Target: Version 5.0
I think you replaced this accidentally.

2023-03-13 09:12 UTC, confluence commented on shared/defs.proto
> +    sfixed32 dir_y = 2;
I would change "Direction" to "Spatial" here.

2023-03-13 09:18 UTC, confluence requested changes

2023-03-13 09:18 UTC, confluence commented on shared/defs.proto
> +    sfixed32 dir_y = 2;
I would also rename `dir_x` and `dir_y` to `spatial_x` and `spatial_y`.

2023-03-15 07:55 UTC, confluence approved these changes

2023-03-22 10:41 UTC, merged